### ISSUE TITLE
properties with the same names on child objects throw exceptions

### ISSUE THREAD

**Issue by condron** [Aardware-Ltd/Xunit.ScenarioReporting#26]
if a nested value type has repeated property names it throw an exception

**Comment by jageall** [comment]
having trouble reproducing this, do you have an example I can use?
I tried the following structure:

`struct ClassWithChildrenHavingSameNames
        {
            public string Text { get; set; }
            public ChildWithSameNames Child { get; set; }
            public struct ChildWithSameNames
            {
                public string Text { get; set; }
                public string Child { get; set; }
            }
        }`

**Comment by condron** [comment]
just remove the ignores from the eventstore scenario runner.
